# This file is used to install packages used by the Streamlit App.
# For more details, refer to https://docs.snowflake.com/en/developer-guide/streamlit/create-streamlit-sql#label-streamlit-install-packages-manual

channels:
    - snowflake
dependencies:
    - streamlit=1.35.0
    - scikit-learn=1.3.0
    - snowflake-snowpark-python
    - pandas=2.0.3
